# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-06 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CepidName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cepid_name', models.CharField(default=b'Meu Cepid', max_length=255, verbose_name='CEPID name')),
            ],
            options={
                'verbose_name': 'Cepid name',
                'permissions': (('change_cepid_name', 'Can change the Cepid name.'),),
            },
        ),
        migrations.CreateModel(
            name='PosterImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_image', models.ImageField(upload_to=b'')),
            ],
            options={
                'verbose_name': 'Poster image',
                'permissions': (('change_poster_image', 'Can change the poster image.'),),
            },
        ),
        migrations.CreateModel(
            name='ProcessNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_number', models.CharField(default=b'0000-000/00', max_length=255, verbose_name='Process number')),
            ],
            options={
                'verbose_name': 'Process number',
                'permissions': (('change_process_number', 'Can change the process number.'),),
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_image', models.ImageField(upload_to=b'')),
            ],
            options={
                'verbose_name': 'QR code',
                'permissions': (('change_qr_code', 'Can change the QR code.'),),
            },
        ),
    ]
