# Generated by Django 2.2.5 on 2019-09-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CepidName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cepid_name', models.CharField(default='Meu Cepid', max_length=255, verbose_name='CEPID name')),
            ],
            options={
                'verbose_name': 'Cepid name',
                'permissions': (('change_cepid_name', 'Can change the Cepid name.'),),
            },
        ),
        migrations.CreateModel(
            name='PrincipalInvestigator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Principal Investigator',
                'permissions': (('change_principal_investigator', 'Can change the Principal Investigator.'),),
            },
        ),
        migrations.CreateModel(
            name='ProcessNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_number', models.CharField(
                    default='0000/00000-0',
                    max_length=255,
                    verbose_name='Process number')),
            ],
            options={
                'verbose_name': 'Process number',
                'permissions': (('change_process_number', 'Can change the process number.'),),
            },
        ),
    ]
