# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-08 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processnumber',
            name='process_number',
            field=models.CharField(default=b'0000/00000-0', max_length=255, verbose_name='Process number'),
        ),
    ]
