# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-16 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_default_process_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PosterImage',
        ),
        migrations.DeleteModel(
            name='QRCode',
        ),
    ]
