# Generated by Django 2.2.5 on 2019-11-12 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dissemination', '0002_auto_20190911_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='external',
            name='media_outlet',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='dissemination.ExternalMediaOutlet',
                verbose_name='Media outlet'),
        ),
        migrations.AlterField(
            model_name='internal',
            name='media_outlet',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='dissemination.InternalMediaOutlet',
                verbose_name='Media outlet'),
        ),
    ]
