# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissemination', '0002_auto_20160503_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissemination',
            name='topic',
            field=models.ManyToManyField(blank=True, to='dissemination.Topic', verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='external',
            name='author',
            field=models.ManyToManyField(blank=True, to='person.Person', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='internal',
            name='author',
            field=models.ManyToManyField(blank=True, to='person.Person', verbose_name='Author'),
        ),
    ]
