# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_auto_20160520_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view_reports', 'Can see reports'), ('add_content', 'Can add contents'),
                                     ('create_documents', 'Can create documents')), 'verbose_name': 'User',
                     'verbose_name_plural': 'Users'},
        ),
    ]
