# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-02 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_set_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_nira_admin',
            field=models.BooleanField(default=False,
                                      help_text='Designates whether this user has special permissions, e.g. add '
                                                'content on behalf of another user.', verbose_name='NIRA admin'),
        ),
    ]
