# Generated by Django 2.2.5 on 2019-09-11 16:34

from django.db import migrations, models
import django.db.models.deletion
import person.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0008_city_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('acronym', models.CharField(blank=True, max_length=50, null=True, verbose_name='Acronym')),
                ('zipcode', models.CharField(blank=True, max_length=9, verbose_name='Zip Code')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('street_complement', models.CharField(blank=True, max_length=255, verbose_name='Complement')),
                ('number', models.CharField(blank=True, max_length=10, verbose_name='Number')),
                ('district', models.CharField(blank=True, max_length=255, verbose_name='District')),
                ('belongs_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.Institution', verbose_name='Belongs to')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='InstitutionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Type of institution',
                'verbose_name_plural': 'Types of institution',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_pt_br', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, unique=True, verbose_name='Full name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('rg', models.CharField(blank=True, max_length=12, null=True, verbose_name='RG')),
                ('cpf', models.CharField(blank=True, max_length=15, null=True, validators=[person.models.validate_cpf], verbose_name='CPF')),
                ('passport', models.CharField(blank=True, max_length=12, null=True, verbose_name='Passport')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone')),
                ('cellphone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Cell Phone')),
                ('zipcode', models.CharField(blank=True, max_length=9, null=True, verbose_name='Zip Code')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('street_complement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complement')),
                ('number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Number')),
                ('district', models.CharField(blank=True, max_length=255, null=True, verbose_name='District')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=255, null=True, verbose_name='State')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Signature')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.Institution', verbose_name='Institution')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.Role', verbose_name='Role')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Person',
                'ordering': ('full_name',),
            },
        ),
        migrations.AddField(
            model_name='institution',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.InstitutionType', verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='CitationName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name in bibliographic citation')),
                ('default_name', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, max_length=3, verbose_name='Default name?')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person', verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Citation name',
                'verbose_name_plural': 'Citation name',
                'ordering': ('person',),
            },
        ),
    ]
