# Generated by Django 2.2.5 on 2019-11-12 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='belongs_to',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='person.Institution',
                verbose_name='Belongs to'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='city',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='cities_light.City',
                verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='person.InstitutionType',
                verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='person',
            name='institution',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='person.Institution',
                verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='person.Role',
                verbose_name='Role'),
        ),
    ]
