# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        ('person', '0004_email_max_length_was_increased'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='institution',
            name='district',
            field=models.CharField(blank=True, max_length=255, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='institution',
            name='number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Number'),
        ),
        migrations.AddField(
            model_name='institution',
            name='street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='institution',
            name='street_complement',
            field=models.CharField(blank=True, max_length=255, verbose_name='Complement'),
        ),
        migrations.AddField(
            model_name='institution',
            name='zipcode',
            field=models.CharField(blank=True, max_length=9, verbose_name='Zip Code'),
        ),
    ]
