# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-08 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_add_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Signature'),
        ),
    ]
