# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-09 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_person_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='role',
            name='name_pt_br',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
    ]
