# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seminar',
            old_name='meeting',
            new_name='belongs_to',
        ),
        migrations.RenameField(
            model_name='trainingprogram',
            old_name='meeting',
            new_name='belongs_to',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='participant',
            field=models.ManyToManyField(blank=True, to='person.Person', verbose_name='Participant'),
        ),
    ]
