# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-08 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20160520_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='cepid_event',
            field=models.BooleanField(default=False, verbose_name='Organized by Meu Cepid?'),
        ),
    ]
