# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-16 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_changed_cepid_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminartype',
            name='image',
            field=models.ImageField(blank=True, help_text='Logo for poster. We recommend an image with size 400x100.', null=True, upload_to=b'', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='seminartype',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='QR code with link to some page.', null=True, upload_to=b'', verbose_name='QR Code'),
        ),
    ]
