# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-07 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_alter_field_cepid_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=b'banners/', verbose_name='Banner'),
        ),
    ]
