# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-10 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_meeting_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminartype',
            name='image',
            field=models.ImageField(blank=True, help_text='Logo for poster. We recommend an image with size 400x100.', null=True, upload_to=b'banners/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='seminartype',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='QR code with link to some page.', null=True, upload_to=b'qr_code/', verbose_name='QR Code'),
        ),
    ]
