# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        ('scientific_mission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.DateTimeField(verbose_name='Departure')),
                ('arrival', models.DateTimeField(verbose_name='Arrival')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                       related_name='destination', to='cities_light.City',
                                                       verbose_name='To')),
                ('origin_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin',
                                                  to='cities_light.City', verbose_name='From')),
            ],
        ),
        migrations.AlterModelOptions(
            name='scientificmission',
            options={'ordering': ('-date_of_registration',), 'verbose_name': 'Daily stipend',
                     'verbose_name_plural': 'Daily stipends'},
        ),
        migrations.AddField(
            model_name='scientificmission',
            name='date_of_registration',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='route',
            name='scientific_mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='scientific_mission.ScientificMission'),
        ),
        migrations.AlterField(
            model_name='scientificmission',
            name='arrival',
            field=models.DateTimeField(null=True, verbose_name='Arrival'),
        ),
        migrations.AlterField(
            model_name='scientificmission',
            name='departure',
            field=models.DateTimeField(null=True, verbose_name='Departure'),
        ),
        migrations.AlterField(
            model_name='scientificmission',
            name='destination_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='destination_city', to='cities_light.City',
                                    verbose_name='City of destination'),
        ),
        migrations.AlterField(
            model_name='scientificmission',
            name='origin_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City',
                                    verbose_name='City of origin'),
        ),
    ]
