# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_mission', '0004_remove_fields_from_scientific_mission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ('scientific_mission', 'order')},
        ),
    ]
